networks:
  ntop-net:
    name: ntop-net
    driver: bridge

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: ["--save", "300", "1", "--ignore-warnings", "ARM64-COW-BUG"]
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    networks:
      - ntop-net
    restart: unless-stopped

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    # command: ["--reporting-disabled"]
    environment:
      - INFLUXDB_HTTP_FLUX_ENABLED=true
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    networks:
      - ntop-net
    restart: unless-stopped
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    ports:
      - 3003:3000
    restart: unless-stopped
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/custom:/custom
    networks:
      - ntop-net
  
  ntopng:
    image: ntop/ntopng:stable
    # image: ntop/ntopng_arm64.dev:latest
    container_name: ntopng
    command: ["--community", "-i", "eno0", "--redis", "localhost:6379@0", "--http-port", "3002"]
    volumes:
      - ./ntopng:/var/lib/ntopng
    environment:
      - TZ="Asia/Kolkata"
    network_mode: host
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
      influxdb:
        condition: service_healthy

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   restart: unless-stopped
  #   volumes:
  #     - /opt/nginx/static:/usr/share/nginx/html:ro
  #   networks:
  #     - ntop-net