{
 "title": "ntopng - Long Term",
 "description": "Long-term ntopng data via InfluxDB",
 "time": { "from": "now-24h", "to": "now-1m" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "asns",
    "label": "ASN",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"asn\""
    }
   },
   { "name": "iface_name", "label": "Interface Name", "query": "eno0 : 0" },
   {
    "name": "min_data",
    "label": "Minimum data",
    "query": "All : 0,1 KB : 0.001,10KB : 0.01,100KB : 0.1,1 MB : 1,1 GB : 1000"
   },
   {
    "name": "ouis",
    "label": "OUI",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"mac\""
    }
   },
   {
    "name": "selected_ipa",
    "label": "IP Address",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY=\"host\""
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bandwidth Usage",
   "type": "timeseries",
   "description": "Bandwidth usage on interface ${iface_name:text} (symlog scale)",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "iface:throughput_bps",
     "select": [
      [
       { "params": [ "bps" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1024/1024 * 8" ], "type": "math" },
       { "params": [ "mbps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Per-protocol traffic",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "[[tag_l4proto]]",
     "groupBy": [
      { "params": [ "l4proto::tag" ], "type": "tag" }
     ],
     "measurement": "iface:l4protos",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Daily Usage (IP Address)",
   "type": "table",
   "description": "Daily usage over the last 31 days - The first and last records may be incomplete.",
   "gridPos": { "h": 20, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "host:traffic",
     "query": "SELECT non_negative_difference(max(\"bytes_rcvd\"))  / 1024 / 1024 AS \"received\", non_negative_difference(max(\"bytes_sent\"))  / 1024 / 1024 AS \"sent\" FROM \"host:traffic\" WHERE (\"ifid\"::tag =~ /^$iface_name$/) AND \"host\"::tag =~ /${selected_ipa:pipe}/ AND time >= now() - 31d GROUP BY time(5m), \"host\"::tag tz('$__timezone')",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" },
       { "params": [ "received" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ],
     "tz": "$__timezone"
    }
   ]
  },
  {
   "title": "Traffic By Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "host:traffic",
     "query": "SELECT non_negative_difference(max(\"bytes_rcvd\"))  / 1024 / 1024 AS \"received\", non_negative_difference(max(\"bytes_sent\"))  / 1024 / 1024 * -1 AS \"sent\" FROM \"host:traffic\" WHERE (\"ifid\"::tag =~ /^$iface_name$/) AND $timeFilter GROUP BY time($__interval), \"host\"::tag",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" },
       { "params": [ "received" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024 * -1" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    }
   ]
  },
  { "title": "LAN Host Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Traffic By Time (IP Address)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "mac::tag" ], "type": "tag" }
     ],
     "measurement": "mac:traffic",
     "query": "SELECT non_negative_difference(max(\"bytes_rcvd\"))  / 1024 / 1024 as rcvd, non_negative_difference(max(\"bytes_sent\"))  / 1024 / 1024 * -1 as sent FROM \"host:traffic\" WHERE (\"ifid\"::tag =~ /^$iface_name$/) AND $timeFilter AND \"host\"::tag =~ /${selected_ipa:pipe}/ GROUP BY \"host\"::tag, time($__interval)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative (IP Address)",
   "type": "table",
   "description": "Total number of bytes sent and received <u>by each host</u>.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "mac::tag" ], "type": "tag" }
     ],
     "measurement": "mac:traffic",
     "query": "SELECT non_negative_difference(\"bytes_rcvd\")  / 1024 / 1024 AS \"received\", non_negative_difference(\"bytes_sent\")  / 1024 / 1024 AS \"sent\" FROM \"host:traffic\" WHERE (\"ifid\"::tag =~ /^$iface_name$/) AND $timeFilter GROUP BY \"host\"::tag",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" },
       { "params": [ "received" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic By Time (MAC Address)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$tag_mac $col",
     "groupBy": [
      { "params": [ "mac::tag" ], "type": "tag" }
     ],
     "measurement": "mac:traffic",
     "query": "SELECT non_negative_difference(max(\"bytes_rcvd\"))  / 1024 / 1024 as rcvd, non_negative_difference(max(\"bytes_sent\"))  / 1024 / 1024 * -1 as sent FROM \"mac:traffic\" WHERE (\"ifid\"::tag =~ /^$iface_name$/) AND $timeFilter GROUP BY \"mac\"::tag, time($__interval)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative (MAC Address)",
   "type": "table",
   "description": "Total number of bytes sent and received <u>by each MAC Address</u>.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "mac::tag" ], "type": "tag" }
     ],
     "measurement": "mac:traffic",
     "query": "SELECT non_negative_difference(\"bytes_rcvd\")  / 1024 / 1024 AS \"received\", non_negative_difference(\"bytes_sent\")  / 1024 / 1024 AS \"sent\" FROM \"mac:traffic\" WHERE (\"ifid\"::tag =~ /^$iface_name$/) AND $timeFilter GROUP BY \"mac\"::tag",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" },
       { "params": [ "received" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    },
    {
     "queryText": "SELECT oui, org FROM oui WHERE oui IN ('01:00:5E','01:40:96','01:60:1D','01:80:C2','14:EB:B6','2A:30:34','2E:9E:E4','30:85:A9','30:9C:23','32:D8:8B','33:33:00','33:33:FF','44:00:49','46:1A:4B','66:FF:2A','6A:35:F4','74:DA:38','7C:C2:C6','82:4F:67','86:1B:55','8C:5A:F8','98:B8:E3','A6:15:A2','AA:15:A2','AC:15:A2','B2:15:A2','B6:15:A2','C2:D5:A9','D8:C4:97','DC:E5:5B','EE:4C:36','F8:42:88','FF:FF:FF')",
     "rawQueryText": "SELECT oui, org FROM oui WHERE oui IN (${ouis:singlequote})"
    }
   ]
  },
  { "title": "External Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "External Servers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$tag_asn $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "asn::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "asn:traffic",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024/1024" ], "type": "math" },
       { "params": [ "received" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024/1024*-1" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative",
   "type": "table",
   "description": "Total number of bytes sent and received <u>by an organization</u>.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "asn::tag" ], "type": "tag" }
     ],
     "measurement": "asn:traffic",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024/1024" ], "type": "math" },
       { "params": [ "received" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024/1024" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    },
    {
     "queryText": "-- SELECT CAST(asn as TEXT) as asn, org from ASN4\r\nSELECT CAST(asn as TEXT) as asn, org from ASN4 WHERE asn in (${asns:singlequote})",
     "rawQueryText": "-- SELECT CAST(asn as TEXT) as asn, org from ASN4\r\nSELECT CAST(asn as TEXT) as asn, org from ASN4 WHERE asn in (${asns:singlequote})"
    }
   ]
  },
  { "title": "Geographical Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 16, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country::tag" ], "type": "tag" }
     ],
     "measurement": "country:traffic",
     "select": [
      [
       { "params": [ "bytes_ingress" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" },
       { "params": [ "received" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_egress" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country::tag" ], "type": "tag" }
     ],
     "measurement": "country:traffic",
     "select": [
      [
       { "params": [ "bytes_ingress" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" },
       { "params": [ "received" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_egress" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024 / 1024" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative",
   "type": "table",
   "description": "Total number of ingress/egress bytes <u>for a country</u>.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$tag_asn",
     "groupBy": [
      { "params": [ "country::tag" ], "type": "tag" }
     ],
     "measurement": "country:traffic",
     "select": [
      [
       { "params": [ "bytes_ingress" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024/1024" ], "type": "math" },
       { "params": [ "received" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_egress" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 1024/1024" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
     ]
    }
   ]
  },
  {
   "title": "DNS ($iface_name)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS (Client)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "$col",
       "measurement": "host:dns_qry_sent_rsp_rcvd",
       "select": [
        [
         { "params": [ "replies_ok_pkts" ], "type": "field" },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "ok" ], "type": "alias" }
        ],
        [
         { "params": [ "replies_error_pkts" ], "type": "field" },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "error" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
       ]
      }
     ]
    },
    {
     "title": "DNS (Server)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "$col",
       "measurement": "host:dns_qry_rcvd_rsp_sent",
       "select": [
        [
         { "params": [ "replies_ok_pkts" ], "type": "field" },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "ok" ], "type": "alias" }
        ],
        [
         { "params": [ "replies_error_pkts" ], "type": "field" },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "error" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
       ]
      }
     ]
    },
    {
     "title": "By time (Server)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 85 },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "host:dns_qry_rcvd_rsp_sent",
       "select": [
        [
         { "params": [ "replies_ok_pkts" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "ok" ], "type": "alias" }
        ],
        [
         { "params": [ "replies_error_pkts" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ "error" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "ifid::tag", "operator": "=~", "value": "/^$iface_name$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}